# Generated by Django 3.2.8 on 2021-11-02 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='coverpic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
    ]
