# Generated by Django 3.2.8 on 2021-11-02 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0002_blogs_coverpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='personal',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
