# Generated by Django 3.2.8 on 2021-11-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0003_blogs_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
