# Generated by Django 3.2.8 on 2021-11-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0004_alter_blogs_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(upload_to='galery'),
        ),
    ]
