# Generated by Django 3.2.8 on 2021-11-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0005_alter_gallery_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
