# Generated by Django 3.2.8 on 2021-11-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startblog', '0008_auto_20211109_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
